/**
 * Capability scopes for the tRPC API — what a session class other than `full`
 * may reach.
 *
 * WHY THIS EXISTS: exposing a web UI means a browser session that is NOT the
 * desktop app, NOT the CLI, and NOT a co-located `slay` — reached over the
 * internet, holding a weaker credential than everything that exists today. A
 * scoped session must not be able to read provider API keys, execute arbitrary
 * shell commands, touch the filesystem sandbox, or mint a computer credential,
 * even while it CAN type into an already-running agent (the actual product).
 *
 * THIS FILE IS A SECURITY DOCUMENT, not just data. A reviewer should be able to
 * read `SCOPE_POLICY` top to bottom and know exactly what the web can do. Keep
 * entries grouped by router, keep the router-level comments, and do not let this
 * rot into a diff nobody reads.
 *
 * WHY AN EXPLICIT ALLOWLIST, NOT `.meta()` OR PER-ROUTER DEFAULTS:
 *   - `.meta()` is typed `TMeta | undefined` — an un-annotated procedure yields
 *     `undefined`, which can be MADE to deny at runtime, but nothing forces a
 *     new procedure to carry `.meta()` at authoring time. The failure is
 *     invisible until the UI 403s in production.
 *   - Per-router defaults don't work here: `pty` alone spans `onData` (must be
 *     readable) and `create` (must never be reachable), so you end up with
 *     per-procedure overrides inside the router anyway, with extra indirection.
 *   - An explicit flat map, cross-checked against the live router in
 *     `scopes.test.ts`, gives fail-closed TWICE: an unknown path is `FORBIDDEN`
 *     at runtime (see `trpc.ts`), and a procedure added without being classified
 *     fails CI by name (`scopes.test.ts`'s exhaustiveness check). That second
 *     property is the one `.meta()` cannot give — nothing else in this codebase
 *     forces a future PR to make a security decision before merging.
 *
 * NO ROUTER IMPORTS HERE, deliberately. This file must stay pure data + the
 * vocabulary comments — `scopes.test.ts` is where the coupling to the live
 * `appRouter` happens, in a test, not in production code.
 *
 * @module transport/server/scopes
 */

/**
 * The scope vocabulary. Kept deliberately tiny — a large vocabulary rots.
 *
 *   full  — everything that exists today: the desktop app, the CLI, and any
 *           session resolved via `verifySession` (a real better-auth session,
 *           reached by a bearer or the bootstrap-owner token). A `full`
 *           principal SKIPS the scope check entirely (see `trpc.ts`), so every
 *           existing client is byte-identical to before scopes existed.
 *   read  — observe-only queries and subscriptions. No mutation of any kind.
 *   tasks — task / project / tag / artifact / terminal-tab CRUD. The
 *           collaborative surface a web user actually edits.
 *   agent — speak to an ALREADY-RUNNING agent session (type into it, read its
 *           output, adjust its runtime settings). Explicitly NOT "choose what
 *           runs" — see the honest-statement block below.
 */
export type Scope = 'full' | 'read' | 'tasks' | 'agent'

/**
 * Every scope a principal may hold. `full` implies every other scope (checked
 * first in the gate, see `trpc.ts`), so a `full` principal never needs the
 * other three listed — but a scoped (non-`full`) principal's `scopes` array may
 * list more than one, e.g. `['read', 'tasks', 'agent']` for a typical web login.
 */
export type PrincipalScope = Scope

/**
 * A procedure's classification — every {@link Scope} PLUS `never`. `never` is
 * not something a principal can hold; it exists only as a policy VALUE, so a
 * procedure can be explicitly marked unreachable by any scoped session rather
 * than merely absent from the map (see `SCOPE_POLICY`'s docstring for why that
 * distinction is load-bearing for the exhaustiveness test).
 */
export type ProcedureScope = Scope | 'never'

/**
 * Per-procedure minimum admitting scope, keyed by the SAME dotted path
 * `appRouter._def.procedures` uses (`<router>.<procedure>`, nested routers
 * flatten fully — e.g. `chat.queue.clear`).
 *
 * `never` is a DELIBERATE entry, not an absence — it is what lets
 * `scopes.test.ts` assert every live path was actually considered, rather than
 * merely "not yet granted". A path missing from this map entirely is refused by
 * the runtime gate (fail-closed) AND fails the exhaustiveness test (fail-loud) —
 * see `trpc.ts` and `scopes.test.ts`.
 *
 * ── pty: "speak to an existing session", never "choose what runs" ──────────
 * Granted (`agent`): write/submit/interrupt/resize/touch, every read
 * (getBuffer*, exists, list, getState, sessionList, sessionGetState, chatList,
 * clearBuffer, ackEnsureAlive) and every `on*` subscription.
 * Denied (`never`): `create` (takes `anyInput` — an UNVALIDATED spawn spec, not
 * admitted even narrowed), `kill`, `setShellOverride`, `setTheme`,
 * `validate`, `warmSetProjectTabCounts`, every `modes*` procedure, and every
 * `test*` procedure.
 *
 * WRITTEN DOWN, NOT DISCOVERED LATER: `pty.onData` (and `chat.onEvent`) can now
 * take an optional `sessionIds`/`tabIds` filter (routers/pty.ts, routers/chat.ts)
 * that drops non-matching events server-side — but the filter is OPT-IN. A
 * caller (any caller, any scope, `agent` included) that subscribes with no
 * filter still receives every byte of every live session on the hub, exactly
 * as before the filter existed. So `agent`/`read` granting this subscription is
 * necessarily a grant to "every terminal on the hub" until the WEB CLIENT
 * itself always passes `sessionIds` scoped to what that session's user may
 * see — the scope system has no way to enforce that from the server side,
 * since the filter is a bandwidth optimization, not an authorization boundary.
 *
 * ── chat: the same split, applied to its own create-shaped procedures ──────
 * `start` / `reset` / `abortAndPop` all take `chatCreateOpts` — an
 * attacker-chosen `mode` + `cwd` (+ optional provider-flag override) that
 * either creates a fresh session or re-creates one with different parameters.
 * That is the identical risk class to `pty.create`, so all three are `never`
 * despite chat otherwise being granted wholesale. `kill` / `remove` take only a
 * `tabId` (no mode/cwd choice) but are denied FOR SYMMETRY with `pty.kill`:
 * ending the host process is reserved for `full`; steering the agent already
 * running in it is what `agent` scope is for. Runtime-setting changes on an
 * existing session (`setMode`, `setModel`, `setEffort`, `setFastMode`,
 * `setCollaboration`) stay granted — no cwd/binary choice involved.
 *
 * ── computers: visibility-filtered reads only ───────────────────────────────
 * `list` / `resolveTaskComputer` / `onStatusChange` are granted as `read` — a
 * web client cannot render a task without showing which computer it runs on,
 * and these are filtered in the STORE by `computers/server/visibility.ts`
 * before scopes ever see them, so a scoped session sees exactly what its user
 * may see. Every mutation is `never`, INCLUDING `setTaskComputer` /
 * `setProjectDefaultComputer` — binding a task to a computer is choosing WHERE
 * CODE RUNS (`visibility.ts` calls this out explicitly as code execution in
 * that account), which is a materially different action from watching and
 * steering an agent that is already placed.
 *
 * ── granted wholesale (the collaborative CRUD surface) ─────────────────────
 * `task.*`, `projects.*`, `projectGroups.*`, `tags.*`, `artifacts.*`,
 * `taskTerminals.*` → `tasks`. `chat.*` (minus the five denials above) → `agent`.
 * `agentPrompts.list/onChanged`, `agentSessions.list/onChanged`,
 * `agentTurns.list/onChanged`, `history.*`, `usageAnalytics.*`,
 * `agentLifecycle.onEvent`, `notify.onTasksChanged` → `read`.
 * `task.testRecordPendingSpawn` is carved out to `never` (a test hook, not part
 * of the CRUD surface it happens to live in).
 *
 * ── granted narrowly (theme) ─────────────────────────────────────────────────
 * `settings.getEffectiveTheme` / `getThemeSource` / `onThemeChanged` /
 * `setTheme` → `read`. A browser needs to render the correct light/dark theme;
 * the rest of `settings.*` (an arbitrary KV store of unknown scope) is `never`.
 *
 * ── denied wholesale (infra, danger, or simply out of Phase-1 scope) ───────
 * Every procedure in `app` (native window/browser-panel/floating-agent/webview
 * control — nothing here is meaningful from a browser tab), `aiConfig`
 * (provider API keys), `integrations` (credential-store backed), `worktrees`
 * (git mutations + `mergeWithAI`/`analyzeConflict`), `processes`, `automations`,
 * `menu`, `workspace` (includes `setAllowedRoots` — mutates the fs sandbox
 * itself), `fileEditor` (raw filesystem writes), `testPanel`, `diagnostics`,
 * `feedback`, `notify` (minus the one exception above), `telemetry`, `template`,
 * `hub` (minus `describe`, which is reachable regardless — see below).
 *
 * `hub.describe` is built on `openProcedure` (see `trpc.ts`), so it never
 * reaches the scope gate at all — it is listed here as `read` only so the
 * exhaustiveness test has an entry for every live path, not because the value
 * is ever consulted for it.
 */
export const SCOPE_POLICY: Record<string, ProcedureScope> = {
  'agentLifecycle.onEvent': 'read',
  'agentPrompts.list': 'read',
  'agentPrompts.onChanged': 'read',
  'agentSessions.list': 'read',
  'agentSessions.onChanged': 'read',
  'agentTurns.list': 'read',
  'agentTurns.onChanged': 'read',
  'aiConfig.checkSlayConfigured': 'never',
  'aiConfig.checkSyncStatus': 'never',
  'aiConfig.createComputerFile': 'never',
  'aiConfig.createItem': 'never',
  'aiConfig.deleteComputerFile': 'never',
  'aiConfig.deleteContextFile': 'never',
  'aiConfig.deleteItem': 'never',
  'aiConfig.discoverComputerMcpConfigs': 'never',
  'aiConfig.discoverContextFiles': 'never',
  'aiConfig.discoverMcpConfigs': 'never',
  'aiConfig.getComputerFiles': 'never',
  'aiConfig.getContextTree': 'never',
  'aiConfig.getExpectedSkillContent': 'never',
  'aiConfig.getItem': 'never',
  'aiConfig.getLibraryInstructions': 'never',
  'aiConfig.getProjectInstructionVariant': 'never',
  'aiConfig.getProjectProviders': 'never',
  'aiConfig.getProjectSkillsStatus': 'never',
  'aiConfig.getProjectStaleSkillCount': 'never',
  'aiConfig.getProjectsStaleSkillCounts': 'never',
  'aiConfig.getRootInstructions': 'never',
  'aiConfig.listInstructionVariants': 'never',
  'aiConfig.listItems': 'never',
  'aiConfig.listProjectSelections': 'never',
  'aiConfig.listProviders': 'never',
  'aiConfig.loadLibraryItem': 'never',
  'aiConfig.marketplace.addRegistry': 'never',
  'aiConfig.marketplace.checkUpdates': 'never',
  'aiConfig.marketplace.ensureFresh': 'never',
  'aiConfig.marketplace.installSkill': 'never',
  'aiConfig.marketplace.listEntries': 'never',
  'aiConfig.marketplace.listRegistries': 'never',
  'aiConfig.marketplace.refreshAll': 'never',
  'aiConfig.marketplace.refreshRegistry': 'never',
  'aiConfig.marketplace.removeRegistry': 'never',
  'aiConfig.marketplace.toggleRegistry': 'never',
  'aiConfig.marketplace.unlinkSkill': 'never',
  'aiConfig.marketplace.updateSkill': 'never',
  'aiConfig.needsSync': 'never',
  'aiConfig.pullProviderInstructions': 'never',
  'aiConfig.pullProviderSkill': 'never',
  'aiConfig.pushProviderInstructions': 'never',
  'aiConfig.readContextFile': 'never',
  'aiConfig.readProviderInstructions': 'never',
  'aiConfig.readProviderSkill': 'never',
  'aiConfig.reconcileProjectSkills': 'never',
  'aiConfig.removeComputerMcpServer': 'never',
  'aiConfig.removeMcpServer': 'never',
  'aiConfig.removeProjectSelection': 'never',
  'aiConfig.renameContextFile': 'never',
  'aiConfig.saveInstructionsContent': 'never',
  'aiConfig.saveLibraryInstructions': 'never',
  'aiConfig.saveRootInstructions': 'never',
  'aiConfig.setProjectInstructionVariant': 'never',
  'aiConfig.setProjectProviders': 'never',
  'aiConfig.setProjectSelection': 'never',
  'aiConfig.setupSlay': 'never',
  'aiConfig.syncAll': 'never',
  'aiConfig.syncLinkedFile': 'never',
  'aiConfig.toggleProvider': 'never',
  'aiConfig.unlinkFile': 'never',
  'aiConfig.updateItem': 'never',
  'aiConfig.writeComputerMcpServer': 'never',
  'aiConfig.writeComputerSkill': 'never',
  'aiConfig.writeContextFile': 'never',
  'aiConfig.writeMcpServer': 'never',
  'app.auth.githubSystemSignIn': 'never',
  'app.auth.onCallback': 'never',
  'app.backup.create': 'never',
  'app.backup.delete': 'never',
  'app.backup.getSettings': 'never',
  'app.backup.list': 'never',
  'app.backup.rename': 'never',
  'app.backup.restore': 'never',
  'app.backup.revealInFinder': 'never',
  'app.backup.setSettings': 'never',
  'app.browser.activateExtension': 'never',
  'app.browser.closeDevTools': 'never',
  'app.browser.createView': 'never',
  'app.browser.destroyAllForTask': 'never',
  'app.browser.destroyView': 'never',
  'app.browser.discoverBrowserExtensions': 'never',
  'app.browser.executeJs': 'never',
  'app.browser.findInPage': 'never',
  'app.browser.focus': 'never',
  'app.browser.getActualNativeBounds': 'never',
  'app.browser.getAllViewIds': 'never',
  'app.browser.getBounds': 'never',
  'app.browser.getExtensions': 'never',
  'app.browser.getNativeChildViewCount': 'never',
  'app.browser.getPartition': 'never',
  'app.browser.getUrl': 'never',
  'app.browser.getViewVisible': 'never',
  'app.browser.getViewsForTask': 'never',
  'app.browser.getWebContentsId': 'never',
  'app.browser.getZoomFactor': 'never',
  'app.browser.goBack': 'never',
  'app.browser.goForward': 'never',
  'app.browser.hideAll': 'never',
  'app.browser.importExtension': 'never',
  'app.browser.insertCss': 'never',
  'app.browser.isAllHidden': 'never',
  'app.browser.isDevToolsOpen': 'never',
  'app.browser.isFocused': 'never',
  'app.browser.isViewNativelyVisible': 'never',
  'app.browser.listViews': 'never',
  'app.browser.loadExtension': 'never',
  'app.browser.navigate': 'never',
  'app.browser.onCreateTaskFromLink': 'never',
  'app.browser.onEvent': 'never',
  'app.browser.onFocused': 'never',
  'app.browser.onShortcut': 'never',
  'app.browser.openDevTools': 'never',
  'app.browser.reload': 'never',
  'app.browser.removeCss': 'never',
  'app.browser.removeExtension': 'never',
  'app.browser.reparentToCurrentWindow': 'never',
  'app.browser.sendInputEvent': 'never',
  'app.browser.setBounds': 'never',
  'app.browser.setHandoffPolicy': 'never',
  'app.browser.setKeyboardPassthrough': 'never',
  'app.browser.setLocked': 'never',
  'app.browser.setVisible': 'never',
  'app.browser.setZoom': 'never',
  'app.browser.showAll': 'never',
  'app.browser.stop': 'never',
  'app.browser.stopFindInPage': 'never',
  'app.clipboard.hasFiles': 'never',
  'app.clipboard.readFilePaths': 'never',
  'app.clipboard.writeFilePaths': 'never',
  'app.dialog.showOpenDialog': 'never',
  'app.exportImport.exportAll': 'never',
  'app.exportImport.exportProject': 'never',
  'app.exportImport.import': 'never',
  'app.exportImport.testExportAllToPath': 'never',
  'app.exportImport.testExportProjectToPath': 'never',
  'app.exportImport.testImportFromPath': 'never',
  'app.exportImport.testSetTaskParent': 'never',
  'app.feedback.addMessage': 'never',
  'app.feedback.createThread': 'never',
  'app.feedback.deleteThread': 'never',
  'app.feedback.getMessages': 'never',
  'app.feedback.listThreads': 'never',
  'app.feedback.updateThreadDiscordId': 'never',
  'app.files.pathExists': 'never',
  'app.files.saveTempImage': 'never',
  'app.floatingAgent.detach': 'never',
  'app.floatingAgent.getConfig': 'never',
  'app.floatingAgent.getSession': 'never',
  'app.floatingAgent.getState': 'never',
  'app.floatingAgent.onCollapseChanged': 'never',
  'app.floatingAgent.onSessionChanged': 'never',
  'app.floatingAgent.onState': 'never',
  'app.floatingAgent.reattach': 'never',
  'app.floatingAgent.resetSize': 'never',
  'app.floatingAgent.setEnabled': 'never',
  'app.floatingAgent.setPanelOpen': 'never',
  'app.floatingAgent.setSessionId': 'never',
  'app.floatingAgent.toggleCollapse': 'never',
  'app.leaderboard.getLocalStats': 'never',
  'app.meta.adjustZoom': 'never',
  'app.meta.checkCliInstalled': 'never',
  'app.meta.checkForUpdates': 'never',
  'app.meta.getProtocolClientStatus': 'never',
  'app.meta.getRendererZoomFactor': 'never',
  'app.meta.getSidecarStatus': 'never',
  'app.meta.getTrpcPort': 'never',
  'app.meta.getVersion': 'never',
  'app.meta.getZoomFactor': 'never',
  'app.meta.installCli': 'never',
  'app.meta.isLoopModeEnabled': 'never',
  'app.meta.isTestsPanelEnabled': 'never',
  'app.meta.restartForUpdate': 'never',
  'app.meta.revealSidecarLog': 'never',
  'app.meta.setLabFlag': 'never',
  'app.screenshot.captureView': 'never',
  'app.shell.openExternal': 'never',
  'app.shell.openPath': 'never',
  'app.shortcuts.changed': 'never',
  'app.taskWindows.claimAndCloseOther': 'never',
  'app.taskWindows.claimPanel': 'never',
  'app.taskWindows.claimSession': 'never',
  'app.taskWindows.close': 'never',
  'app.taskWindows.getOwnership': 'never',
  'app.taskWindows.getPrimaryActive': 'never',
  'app.taskWindows.getWindowId': 'never',
  'app.taskWindows.list': 'never',
  'app.taskWindows.onListChanged': 'never',
  'app.taskWindows.onOwnershipChanged': 'never',
  'app.taskWindows.onPanelCloseRequest': 'never',
  'app.taskWindows.onPanelsReleasedOnClose': 'never',
  'app.taskWindows.onPrimaryActiveChanged': 'never',
  'app.taskWindows.open': 'never',
  'app.taskWindows.releaseAllForTask': 'never',
  'app.taskWindows.releasePanel': 'never',
  'app.taskWindows.setPrimaryActive': 'never',
  'app.usage.fetch': 'never',
  'app.usage.test': 'never',
  'app.webview.closeDevTools': 'never',
  'app.webview.disableDeviceEmulation': 'never',
  'app.webview.enableDeviceEmulation': 'never',
  'app.webview.isDevToolsOpened': 'never',
  'app.webview.onShortcut': 'never',
  'app.webview.openDevToolsBottom': 'never',
  'app.webview.openDevToolsDetached': 'never',
  'app.webview.registerBrowserTab': 'never',
  'app.webview.registerShortcuts': 'never',
  'app.webview.setActiveBrowserTab': 'never',
  'app.webview.setDesktopHandoffPolicy': 'never',
  'app.webview.setKeyboardPassthrough': 'never',
  'app.webview.unregisterBrowserTab': 'never',
  'app.window.close': 'never',
  'app.window.focusRenderer': 'never',
  'app.window.getContentBounds': 'never',
  'app.window.getDisplayScaleFactor': 'never',
  'app.window.setTrafficLightPosition': 'never',
  'app.window.setWindowButtonVisibility': 'never',
  'artifacts.cleanupTask': 'tasks',
  'artifacts.create': 'tasks',
  'artifacts.delete': 'tasks',
  'artifacts.downloadAllAsZip': 'tasks',
  'artifacts.downloadAsHtml': 'tasks',
  'artifacts.downloadAsPdf': 'tasks',
  'artifacts.downloadAsPng': 'tasks',
  'artifacts.downloadFile': 'tasks',
  'artifacts.downloadFolder': 'tasks',
  'artifacts.foldersCreate': 'tasks',
  'artifacts.foldersDelete': 'tasks',
  'artifacts.foldersGetByTask': 'tasks',
  'artifacts.foldersGetOrCreateByName': 'tasks',
  'artifacts.foldersReorder': 'tasks',
  'artifacts.foldersUpdate': 'tasks',
  'artifacts.get': 'tasks',
  'artifacts.getByTask': 'tasks',
  'artifacts.getFilePath': 'tasks',
  'artifacts.getMtime': 'tasks',
  'artifacts.onContentChanged': 'tasks',
  'artifacts.pasteFiles': 'tasks',
  'artifacts.readContent': 'tasks',
  'artifacts.reorder': 'tasks',
  'artifacts.update': 'tasks',
  'artifacts.upload': 'tasks',
  'artifacts.uploadBlob': 'tasks',
  'artifacts.uploadDir': 'tasks',
  'artifacts.versionsCreate': 'tasks',
  'artifacts.versionsDiff': 'tasks',
  'artifacts.versionsList': 'tasks',
  'artifacts.versionsPrune': 'tasks',
  'artifacts.versionsRead': 'tasks',
  'artifacts.versionsRename': 'tasks',
  'artifacts.versionsSetCurrent': 'tasks',
  'automations.clearRuns': 'never',
  'automations.create': 'never',
  'automations.delete': 'never',
  'automations.get': 'never',
  'automations.getByProject': 'never',
  'automations.getRuns': 'never',
  'automations.onChanged': 'never',
  'automations.reorder': 'never',
  'automations.runManual': 'never',
  'automations.toggle': 'never',
  'automations.update': 'never',
  'chat.abortAndPop': 'never',
  'chat.bumpAutocompleteUsage': 'agent',
  'chat.getAutoEligibility': 'agent',
  'chat.getAutocompleteUsage': 'agent',
  'chat.getBufferSince': 'agent',
  'chat.getCollaboration': 'agent',
  'chat.getEffort': 'agent',
  'chat.getFastMode': 'agent',
  'chat.getInfo': 'agent',
  'chat.getMode': 'agent',
  'chat.getModel': 'agent',
  'chat.hydrate': 'agent',
  'chat.inspectPermissions': 'agent',
  'chat.interrupt': 'agent',
  'chat.kill': 'never',
  'chat.listAgents': 'agent',
  'chat.listCommands': 'agent',
  'chat.listFiles': 'agent',
  'chat.listSkills': 'agent',
  'chat.onEvent': 'agent',
  'chat.onExit': 'agent',
  'chat.onQueueChanged': 'agent',
  'chat.onQueueDrained': 'agent',
  'chat.queue.clear': 'agent',
  'chat.queue.list': 'agent',
  'chat.queue.push': 'agent',
  'chat.queue.remove': 'agent',
  'chat.remove': 'never',
  'chat.reset': 'never',
  'chat.respondPermission': 'agent',
  'chat.send': 'agent',
  'chat.sendToolResult': 'agent',
  'chat.setCollaboration': 'agent',
  'chat.setEffort': 'agent',
  'chat.setFastMode': 'agent',
  'chat.setMode': 'agent',
  'chat.setModel': 'agent',
  'chat.start': 'never',
  'chat.supports': 'agent',
  'computers.claim': 'never',
  'computers.delete': 'never',
  'computers.list': 'read',
  'computers.mintJoinToken': 'never',
  'computers.onStatusChange': 'read',
  'computers.renameMachine': 'never',
  'computers.resolveTaskComputer': 'read',
  'computers.revokeComputer': 'never',
  'computers.setProjectDefaultComputer': 'never',
  'computers.setTaskComputer': 'never',
  'computers.setVisibility': 'never',
  'computers.unrevoke': 'never',
  'diagnostics.exportBundle': 'never',
  'diagnostics.getConfig': 'never',
  'diagnostics.recordClientError': 'never',
  'diagnostics.recordClientEvent': 'never',
  'diagnostics.setConfig': 'never',
  'feedback.addMessage': 'never',
  'feedback.createThread': 'never',
  'feedback.deleteThread': 'never',
  'feedback.getMessages': 'never',
  'feedback.listThreads': 'never',
  'feedback.updateThreadDiscordId': 'never',
  'fileEditor.copy': 'never',
  'fileEditor.copyIn': 'never',
  'fileEditor.createDir': 'never',
  'fileEditor.createFile': 'never',
  'fileEditor.delete': 'never',
  'fileEditor.gitStatus': 'never',
  'fileEditor.listAllFiles': 'never',
  'fileEditor.readDir': 'never',
  'fileEditor.readFile': 'never',
  'fileEditor.rename': 'never',
  'fileEditor.searchFiles': 'never',
  'fileEditor.showInFinder': 'never',
  'fileEditor.watch': 'never',
  'fileEditor.writeFile': 'never',
  'history.getAutomationActionRuns': 'read',
  'history.listForTask': 'read',
  'hub.describe': 'read',
  'hub.setLabel': 'never',
  'integrations.applyStatusSync': 'never',
  'integrations.clearProjectConnection': 'never',
  'integrations.clearProjectProvider': 'never',
  'integrations.connectGithub': 'never',
  'integrations.connectJira': 'never',
  'integrations.connectLinear': 'never',
  'integrations.disconnect': 'never',
  'integrations.fetchProviderStatuses': 'never',
  'integrations.getBatchTaskSyncStatus': 'never',
  'integrations.getConnectionUsage': 'never',
  'integrations.getJiraTransitions': 'never',
  'integrations.getLink': 'never',
  'integrations.getProjectConnection': 'never',
  'integrations.getProjectMapping': 'never',
  'integrations.getTaskSyncStatus': 'never',
  'integrations.importGithubIssues': 'never',
  'integrations.importGithubRepositoryIssues': 'never',
  'integrations.importLinearIssues': 'never',
  'integrations.importProviderIssues': 'never',
  'integrations.listConnections': 'never',
  'integrations.listGithubIssues': 'never',
  'integrations.listGithubProjects': 'never',
  'integrations.listGithubRepositories': 'never',
  'integrations.listGithubRepositoryIssues': 'never',
  'integrations.listLinearIssues': 'never',
  'integrations.listLinearProjects': 'never',
  'integrations.listLinearTeams': 'never',
  'integrations.listProviderGroups': 'never',
  'integrations.listProviderIssues': 'never',
  'integrations.listProviderScopes': 'never',
  'integrations.pullTask': 'never',
  'integrations.pushTask': 'never',
  'integrations.pushUnlinkedTasks': 'never',
  'integrations.resyncProviderStatuses': 'never',
  'integrations.setProjectConnection': 'never',
  'integrations.setProjectMapping': 'never',
  'integrations.syncNow': 'never',
  'integrations.testClearGithubMocks': 'never',
  'integrations.testSeedGithubConnection': 'never',
  'integrations.testSetGithubRepositories': 'never',
  'integrations.testSetGithubRepositoryIssues': 'never',
  'integrations.unlinkTask': 'never',
  'integrations.updateConnection': 'never',
  'menu.onBrowserAgentTouched': 'never',
  'menu.onBrowserCreateTab': 'never',
  'menu.onBrowserEnsurePanelOpen': 'never',
  'menu.onCloseActiveTask': 'never',
  'menu.onCloseCurrentFocus': 'never',
  'menu.onCloseTask': 'never',
  'menu.onGoHome': 'never',
  'menu.onNewTemporaryTask': 'never',
  'menu.onOpenArtifact': 'never',
  'menu.onOpenProjectSettings': 'never',
  'menu.onOpenSettings': 'never',
  'menu.onOpenTask': 'never',
  'menu.onReloadApp': 'never',
  'menu.onReloadBrowser': 'never',
  'menu.onScreenshotTrigger': 'never',
  'menu.onSyncSessionId': 'never',
  'menu.onToggleAgentStatusPanel': 'never',
  'menu.onToggleGlobalAgentPanel': 'never',
  'menu.onUpdateStatus': 'never',
  'menu.onZoomFactorChanged': 'never',
  'menu.testEmit': 'never',
  'notify.onEmbeddedServerFailed': 'never',
  'notify.onSettingsChanged': 'never',
  'notify.onTasksChanged': 'read',
  'processes.create': 'never',
  'processes.kill': 'never',
  'processes.killTask': 'never',
  'processes.listAll': 'never',
  'processes.listForTask': 'never',
  'processes.onLog': 'never',
  'processes.onStats': 'never',
  'processes.onStatus': 'never',
  'processes.onTitle': 'never',
  'processes.restart': 'never',
  'processes.spawn': 'never',
  'processes.stop': 'never',
  'processes.update': 'never',
  'projectGroups.create': 'tasks',
  'projectGroups.createFolderWithProjects': 'tasks',
  'projectGroups.delete': 'tasks',
  'projectGroups.list': 'tasks',
  'projectGroups.moveProject': 'tasks',
  'projectGroups.reorderProjectsInGroup': 'tasks',
  'projectGroups.reorderTopLevel': 'tasks',
  'projectGroups.update': 'tasks',
  'projects.create': 'tasks',
  'projects.delete': 'tasks',
  'projects.list': 'tasks',
  'projects.reorder': 'tasks',
  'projects.update': 'tasks',
  'projects.uploadIcon': 'tasks',
  'pty.ackEnsureAlive': 'agent',
  'pty.chatList': 'agent',
  'pty.clearBuffer': 'agent',
  'pty.create': 'never',
  'pty.exists': 'agent',
  'pty.getBuffer': 'agent',
  'pty.getBufferSince': 'agent',
  'pty.getState': 'agent',
  'pty.interrupt': 'agent',
  'pty.kill': 'never',
  'pty.list': 'agent',
  'pty.modesCreate': 'never',
  'pty.modesDelete': 'never',
  'pty.modesGet': 'never',
  'pty.modesList': 'never',
  'pty.modesResetToDefaultState': 'never',
  'pty.modesRestoreDefaults': 'never',
  'pty.modesTest': 'never',
  'pty.modesUpdate': 'never',
  'pty.onData': 'agent',
  'pty.onDevServerDetected': 'agent',
  'pty.onEnsureAlive': 'agent',
  'pty.onExit': 'agent',
  'pty.onHibernateCancelled': 'agent',
  'pty.onHibernateWarn': 'agent',
  'pty.onHibernated': 'agent',
  'pty.onPrompt': 'agent',
  'pty.onResizeNeeded': 'agent',
  'pty.onRespawnSuggested': 'agent',
  'pty.onSessionDetected': 'agent',
  'pty.onStateChange': 'agent',
  'pty.onStats': 'agent',
  'pty.onTitleChange': 'agent',
  'pty.resize': 'agent',
  'pty.sessionGetState': 'agent',
  'pty.sessionList': 'agent',
  'pty.setShellOverride': 'never',
  'pty.setTheme': 'never',
  'pty.submit': 'agent',
  'pty.testEmitExit': 'never',
  'pty.testEmitSessionDetected': 'never',
  'pty.testExecutionContext': 'never',
  'pty.testSetPtyCreateCapture': 'never',
  'pty.testTakePtyCreateOpts': 'never',
  'pty.testTakePtyKillCalls': 'never',
  'pty.touch': 'agent',
  'pty.validate': 'never',
  'pty.warmSetProjectTabCounts': 'never',
  'pty.write': 'agent',
  'settings.get': 'never',
  'settings.getAll': 'never',
  'settings.getEffectiveTheme': 'read',
  'settings.getThemeSource': 'read',
  'settings.onThemeChanged': 'read',
  'settings.set': 'never',
  'settings.setTheme': 'read',
  'tags.create': 'tasks',
  'tags.delete': 'tasks',
  'tags.getAllTaskTagIds': 'tasks',
  'tags.getForTask': 'tasks',
  'tags.list': 'tasks',
  'tags.reorder': 'tasks',
  'tags.setForTask': 'tasks',
  'tags.update': 'tasks',
  'task.addBlocker': 'tasks',
  'task.archive': 'tasks',
  'task.archiveMany': 'tasks',
  'task.create': 'tasks',
  'task.delete': 'tasks',
  'task.deleteConversation': 'tasks',
  'task.deleteMany': 'tasks',
  'task.get': 'tasks',
  'task.getAll': 'tasks',
  'task.getAllBlockedTaskIds': 'tasks',
  'task.getBlockers': 'tasks',
  'task.getBlocking': 'tasks',
  'task.getByProject': 'tasks',
  'task.getSubTasks': 'tasks',
  'task.loadBoardData': 'tasks',
  'task.onChanged': 'tasks',
  'task.removeBlocker': 'tasks',
  'task.reorder': 'tasks',
  'task.reorderPinned': 'tasks',
  'task.resetConversation': 'tasks',
  'task.restore': 'tasks',
  'task.setBlockers': 'tasks',
  'task.setBrowserTabLocked': 'tasks',
  'task.switchConversation': 'tasks',
  'task.testRecordPendingSpawn': 'never',
  'task.unarchive': 'tasks',
  'task.update': 'tasks',
  'task.updateMany': 'tasks',
  'taskTerminals.create': 'tasks',
  'taskTerminals.delete': 'tasks',
  'taskTerminals.ensureMain': 'tasks',
  'taskTerminals.list': 'tasks',
  'taskTerminals.listAutoRestoreTasks': 'tasks',
  'taskTerminals.listHibernatedSessions': 'tasks',
  'taskTerminals.moveToGroup': 'tasks',
  'taskTerminals.onChanged': 'tasks',
  'taskTerminals.split': 'tasks',
  'taskTerminals.update': 'tasks',
  'telemetry.onIpcEvent': 'never',
  'template.create': 'never',
  'template.delete': 'never',
  'template.get': 'never',
  'template.getByProject': 'never',
  'template.setDefault': 'never',
  'template.update': 'never',
  'testPanel.applyProfile': 'never',
  'testPanel.createCategory': 'never',
  'testPanel.createLabel': 'never',
  'testPanel.deleteCategory': 'never',
  'testPanel.deleteLabel': 'never',
  'testPanel.deleteProfile': 'never',
  'testPanel.getCategories': 'never',
  'testPanel.getFileLabels': 'never',
  'testPanel.getFileNotes': 'never',
  'testPanel.getLabels': 'never',
  'testPanel.getProfiles': 'never',
  'testPanel.reorderCategories': 'never',
  'testPanel.saveProfile': 'never',
  'testPanel.scanFiles': 'never',
  'testPanel.setFileNote': 'never',
  'testPanel.toggleFileLabel': 'never',
  'testPanel.updateCategory': 'never',
  'testPanel.updateLabel': 'never',
  'usageAnalytics.query': 'read',
  'usageAnalytics.refresh': 'read',
  'usageAnalytics.taskCost': 'read',
  'workspace.forgetProjectPath': 'never',
  'workspace.listDir': 'never',
  'workspace.listRoots': 'never',
  'workspace.mkdir': 'never',
  'workspace.pathExists': 'never',
  'workspace.resolveProjectPath': 'never',
  'workspace.setAllowedRoots': 'never',
  'workspace.setProjectPath': 'never',
  'worktrees.abortMerge': 'never',
  'worktrees.abortRebase': 'never',
  'worktrees.addPrComment': 'never',
  'worktrees.analyzeConflict': 'never',
  'worktrees.applyStash': 'never',
  'worktrees.branchFromStash': 'never',
  'worktrees.checkGhInstalled': 'never',
  'worktrees.checkoutBranch': 'never',
  'worktrees.commitFiles': 'never',
  'worktrees.continueRebase': 'never',
  'worktrees.copyIgnoredFiles': 'never',
  'worktrees.createBranch': 'never',
  'worktrees.createPr': 'never',
  'worktrees.createStash': 'never',
  'worktrees.createWorktree': 'never',
  'worktrees.deleteBranch': 'never',
  'worktrees.detectChildRepos': 'never',
  'worktrees.detectWorktrees': 'never',
  'worktrees.discardFile': 'never',
  'worktrees.dropStash': 'never',
  'worktrees.editPrComment': 'never',
  'worktrees.fetch': 'never',
  'worktrees.getAheadBehind': 'never',
  'worktrees.getAheadBehindUpstream': 'never',
  'worktrees.getCommitDag': 'never',
  'worktrees.getCommitsBeforeRef': 'never',
  'worktrees.getCommitsSince': 'never',
  'worktrees.getConflictContent': 'never',
  'worktrees.getConflictedFiles': 'never',
  'worktrees.getCurrentBranch': 'never',
  'worktrees.getDefaultBranch': 'never',
  'worktrees.getDiffStats': 'never',
  'worktrees.getFileDiff': 'never',
  'worktrees.getGhUser': 'never',
  'worktrees.getIgnoredFileTree': 'never',
  'worktrees.getMergeBase': 'never',
  'worktrees.getMergeContext': 'never',
  'worktrees.getPrByUrl': 'never',
  'worktrees.getPrComments': 'never',
  'worktrees.getPrDiff': 'never',
  'worktrees.getRebaseProgress': 'never',
  'worktrees.getRecentCommits': 'never',
  'worktrees.getRemoteUrl': 'never',
  'worktrees.getResolvedCommitDag': 'never',
  'worktrees.getResolvedForkGraph': 'never',
  'worktrees.getResolvedRecentCommits': 'never',
  'worktrees.getResolvedUpstreamGraph': 'never',
  'worktrees.getStashDiff': 'never',
  'worktrees.getStatusSummary': 'never',
  'worktrees.getUntrackedFileDiff': 'never',
  'worktrees.getWorkingDiff': 'never',
  'worktrees.getWorktreeMetadata': 'never',
  'worktrees.hasGithubRemote': 'never',
  'worktrees.hasUncommittedChanges': 'never',
  'worktrees.init': 'never',
  'worktrees.isDirty': 'never',
  'worktrees.isGitRepo': 'never',
  'worktrees.isMergeInProgress': 'never',
  'worktrees.isRebaseInProgress': 'never',
  'worktrees.listBranches': 'never',
  'worktrees.listBranchesDetailed': 'never',
  'worktrees.listOpenPrs': 'never',
  'worktrees.listProjectRepos': 'never',
  'worktrees.listRemoteBranches': 'never',
  'worktrees.listStashes': 'never',
  'worktrees.mergeFrom': 'never',
  'worktrees.mergeIntoParent': 'never',
  'worktrees.mergePr': 'never',
  'worktrees.mergeWithAI': 'never',
  'worktrees.onCreateWorktreePhase': 'never',
  'worktrees.onDiffChanged': 'never',
  'worktrees.onDiffWatchFailed': 'never',
  'worktrees.popStash': 'never',
  'worktrees.pruneRemote': 'never',
  'worktrees.pull': 'never',
  'worktrees.push': 'never',
  'worktrees.rebaseOnto': 'never',
  'worktrees.removeWorktree': 'never',
  'worktrees.resolveChildBranches': 'never',
  'worktrees.resolveCopyBehavior': 'never',
  'worktrees.revealInFinder': 'never',
  'worktrees.skipRebaseCommit': 'never',
  'worktrees.stageAll': 'never',
  'worktrees.stageFile': 'never',
  'worktrees.unstageAll': 'never',
  'worktrees.unstageFile': 'never',
  'worktrees.watchStart': 'never',
  'worktrees.watchStop': 'never',
  'worktrees.writeResolvedFile': 'never'
}

/**
 * Resolve the minimum scope a path requires. `undefined` (path not in the
 * policy) is treated as `never` by the caller (`trpc.ts`) — this function
 * itself does not special-case that, so the caller's fail-closed behavior is
 * visible at the call site rather than hidden in here.
 */
export function requiredScope(path: string): ProcedureScope | undefined {
  return SCOPE_POLICY[path]
}

/**
 * Whether a principal holding `scopes` may call `path`. `full` always passes
 * (skips the policy entirely — every existing client stays byte-identical).
 * An unclassified path (not in `SCOPE_POLICY`) is refused — `scopes.test.ts`
 * asserts no live path is ever in that state.
 */
export function isPathAllowed(scopes: readonly Scope[], path: string): boolean {
  if (scopes.includes('full')) return true
  const required = requiredScope(path)
  if (required === undefined || required === 'never') return false
  return scopes.includes(required)
}
