pub const HOME: &str = "TERMINAL_JARVIS_HOME";
pub const CATALOG: &str = "TERMINAL_JARVIS_CATALOG";
pub const GATES: &str = "TERMINAL_JARVIS_GATES";
pub const DISTRIBUTION: &str = "TERMINAL_JARVIS_DISTRIBUTION";
pub const WRAPPER: &str = "TERMINAL_JARVIS_WRAPPER";
pub const XDG_CONFIG_HOME: &str = "XDG_CONFIG_HOME";
